### ISSUE TITLE
esp8266 support?

### ISSUE THREAD

**Issue by manvir-singh** [Jeija/esp32free80211#1]
Does this work on an esp8266?

**Comment by Jeija** [comment]
No, but it is not necessary for the ESP8266. Earlier versions of the esp8266 non-OS SDK had a `wifi_send_pkt_freedom()` function builtin that was removed later given the potential for abuse. But it seems like [some people patched it back into SDK version 2.0](https://github.com/cnlohr/esp8266rawpackets/issues/7) and there is already [code out there for the ESP8266 that does the same thing](https://github.com/markszabo/FakeBeaconESP8266).

So it's propably not that easy to get it running on an ESP8266 with the current SDK version, but you should be able to patch something together.
