### ISSUE TITLE
Not work with latest esp-idf

### ISSUE THREAD

**Issue by Nicholas3388** [Jeija/esp32free80211#3]
Hi, the esp32free80211 is not work with the latest esp-idf. Is it possible to fix it?

**Comment by Jeija** [comment]
It might be possible to fix. I see two approaches here:
* Reverse engineer the new `ieee80211_freedom_output` and figure out why it isn't working anymore
* Extract the old `ieee80211_freedom_output` from an old esp32-wifi-lib version and link it with this project

The first solution is cleaner, but it means reverse enginnering the new `ieee80211_freedom_output`. You could do this by decompiling your compiled ELF file (`xtensa-esp32-elf-objdump -D esp32free80211.elf`), reading up on the xtensa instruction set and trying to decode what `ieee80211_freedom_output` is doing and where it fails. Running the code on the ESP32 will give you the program counter `PC` as well as an error description and register values when the program crashes. I might be able to do this myself at some point, but I can't promise when that will be.

**Comment by Nicholas3388** [comment]
@Jeija  Thanks for you advice. I'll try to reverse engineer

**Comment by chaotaklon** [comment]
Hi,
Can you tell me more about how to compile it? You have mentioned it needs specific version of esp32-wifi-lib, but what I see is it depends on esp-idf repository only. My error message is "undefined reference to `ieee80211_freedom_output'".

Alan

**Comment by JanLochi** [comment]
@chaotaklon I used a specific tag of esp-idf, I think it was v2.0, which will use a working version of esp32-wifi-lib.

**Comment by chaotaklon** [comment]
@JanLochi
Thanks for your quick response. It works for me. In esp-idf repo, type the following cmd:
$ git checkout tags/v2.0
$ git submodule update --init --recursive

**Comment by malaimoo** [comment]
@Jeija Reverse engineer is a good idea!

**Comment by Jeija** [comment]
It's also mentioned in the README now, but in case someone didn't notice: Please use https://github.com/Jeija/esp32-80211-tx instead if you want to use the latest esp-idf.
