### ISSUE TITLE
I want to send beacons using this function and receive via wifi in other esp32!

### ISSUE THREAD

**Issue by akshar001** [Jeija/esp32free80211#9]
Can we do that?

**Comment by Jeija** [comment]
Yes, that should be possible. Mind that this repo is obsolete when using up-to-date esp-idf versions, please use https://github.com/Jeija/esp32-80211-tx instead. Other than that, you can e.g. use [promiscous mode](https://docs.espressif.com/projects/esp-idf/en/latest/api-reference/wifi/esp_wifi.html#_CPPv230esp_wifi_set_promiscuous_rx_cb21wifi_promiscuous_cb_t) on the ESP32 configured to be the receiver.

**Comment by akshar001** [comment]
Hello @Jeija  thank you for making this library. It's really usefull. What i am specifically asking is by using your https://github.com/Jeija/esp32-80211-tx library we can indeed send beacons but it's only for wifi ssid's and all that. is there any thing like esp32-80211-rx function which will recieve the data of beacons that we have broadcasted?
